version: '3.5'

services:
#  fullstack-app:
#    container_name: app-server
#    #Runs Dockerfile to build the application
#    build: .
#    ports:
#      - "8080:5000"
#    restart: on-failure
#    #Dependencies name base on other services in compose file
#    depends_on:
#      - fullstack-postgres
#    networks:
#      - fullstack
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_PORT=${DB_PORT}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DATABASE_NAME=${DB_NAME}
#      - DB_TYPE=${DB_DRIVER}
  fullstack-postgres:
    image: postgres
    container_name: big-app-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    networks:
      - fullstack

  pgadmin:
    image: dpage/pgadmin4
    container_name: big-app-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge